### ISSUE TITLE
Specify `engines` in `package.json`

### ISSUE THREAD

**Issue by joneshf** [shinnn/install-purescript-cli#1]
The [`complete`][complete] function uses `async`. This package won't work on older versions of node. It needs at least 7.6.0 (as this was where async/await support was added). Could this be made explicit by adding the [engines][] field to `package.json`? It would make figuring out things like this [error][] a little easier.

[complete]: https://github.com/shinnn/install-purescript-cli/blob/de6f391d19051052c1fc6278672df96b793dbaa8/index.js#L482
[engines]: https://docs.npmjs.com/files/package.json#engines
[error]: https://travis-ci.org/jystic/purescript-jack/builds/521311399#L502-L516

**Comment by shinnn** [comment]
[The main consumer of this package](https://github.com/purescript-contrib/node-purescript) already has [`engine` field](https://github.com/purescript-contrib/node-purescript/blob/1677406aff8788b1f6b4328773d337a2a083a77b/package.json#L9) and that's enough.

**Comment by shinnn** [comment]
@joneshf What do you mean by 😕?

**Comment by joneshf** [comment]
I'm confused because near as I can tell, `purescript` doesn't require that new a version of `node`, but this package does. This package is documented like anyone can use it, but it doesn't have its dependencies set up properly so that anyone can use it. It's just all kind of confusing to me.

**Comment by shinnn** [comment]
Just post a comment instead of an emoji if you have a definite opinion. 

> `purescript` doesn't require that new a version of node

It does require a newer Node.js because its dependencies use ECMAScript 2018 syntax.

> This package is documented like anyone can use it

True. Anyone can use this package. Anyone who sets their development environment normally can use this package.

Most npm packages isn't documented whether they support Windows 1.0, as well as the runtime whose life is [about to end](https://github.com/nodejs/Release/blob/f4ae92f443f57f4b8f0716859a9a64ba055caac4/README.md#release-schedule).

> it doesn't have its dependencies set up properly

In what point specifically? I'm not sure why a package with broken setup is downloaded thousand of times a week. https://www.npmjs.com/package/purescript

**Comment by joneshf** [comment]
> Just post a comment instead of an emoji if you have a definite opinion.

I didn't "just post a comment" because I thought the conversation was over. I asked for something, you gave your opinion, and closed the issue. You goaded me into more conversation when I didn't really want to have any more and now you're trying to make a point about your opinion.

Your opinion confuses me; that's all there is to it. This is your package and you're free to do whatever you want with it. But it breaks in an unclear way, and I wanted to bring that to your attention. I didn't come here to create conflict.
