### ISSUE TITLE
UX suggestion: rethink "Compression takes a while because a PureScript binary is too large"

### ISSUE THREAD

**Issue by hdgarrood** [shinnn/install-purescript-cli#2]
https://github.com/shinnn/install-purescript-cli/blob/de6f391d19051052c1fc6278672df96b793dbaa8/index.js#L466

I think this copy could be improved a little from a UX perspective: firstly, there is now just one PureScript binary, but since it says "a PureScript binary" as opposed to "the PureScript binary", the implication is that there is more than one binary, which might be confusing. Secondly I'm not sure in what sense the binary is "too large"; the uncompressed Linux binary is 42MB, which I don't think is worth worrying about in 2019 - describing it as "too large" might give people the impression that something has gone wrong when it hasn't really.

**Comment by shinnn** [comment]
Thanks for the suggestion.

> since it says "a PureScript binary" as opposed to "the PureScript binary", the implication is that there is more than one binary, which might be confusing.

I really appreciate this kind of English correction. It's very difficult for me, a non-English speaker, to use definite and indefinite articles properly.

As my understanding, when we speak about a generally acknowledged fact, we should use an indefinite article, for example "a (~~the~~) triangle has three sides". I chose "a" because every version of PureScript is large. However, as it's unnatural for native English speakers, I'll change it to "the".

>  I'm not sure in what sense the binary is "too large"

For example the macOS binary of Node.js v12.0.0, which includes the following features:

* V8, a JavaScript engine
* HTTP/1.1 and HTTP/2 implementation 
* File system operations
* Thread pool
* REPL
* and more

is 39.9 MB.

I think it's reasonable to regard a binary with less features "too large".

**Comment by shinnn** [comment]
The update might be:

```diff
- Compression takes a while because a PureScript binary is too large.
+ Compression takes a while because the PureScript binary is too large for a compiler.
```

**Comment by hdgarrood** [comment]
I don't think this package should really be taking a stance on what an appropriate file size for a compiler is at all, honestly. Is a message even necessary? It didn't take very much time at all to extract it on my computer; the message only flashed up for a moment before it disappeared again. Extracting the linux binary using `tar` takes less than a second for me:

```
$ time tar xzf Downloads/linux64.tar.gz 

real	0m0.290s
user	0m0.283s
sys	0m0.046s
```

**Comment by shinnn** [comment]
What this CLI does in the `write-cache` step is:

1. Compress the downloaded binary with Brotli when the Node.js version is 11.7.0 or newer where [Brotli API](https://nodejs.org/api/zlib.html#zlib_class_zlib_brotlicompress) is available, with Gzip when it's older.
2. Move it to a cache directory.

Probably you use an older version of Node.js. With Node.js v12.0.0, a Brotli supported version, the step actually takes a while.

```
✔ Save the downloaded binary to the npm cache directory (49s)
```

**Comment by shinnn** [comment]
https://github.com/shinnn/install-purescript-cli/commit/bc71b9e00aa7c1ebe598bbcaefad7f0c99037432 and https://github.com/shinnn/install-purescript-cli/commit/684e1a44a03f9db9a341f3e97de578a78a8527c8, finally.
